apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: simple-webapp-docker-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/yguionnet/simple-webapp-docker.git
